Repository SOPT-TEAM6-Aladin/Aladin-AOS, pull requests merged in 2022-11, with the labels that each got.

#2 #1 [chore] Main 뷰 / 피알 연습
  .idea/misc.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: chore, pull request🔥, 영주🐼

#4 #3 [chore] 기초세팅
  .gitignore
  .gradle/7.3.3/checksums/checksums.lock
  .gradle/7.3.3/executionHistory/executionHistory.lock
  .gradle/7.3.3/fileHashes/fileHashes.bin
  .gradle/7.3.3/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/workspace.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/aladinaos/MainActivity.kt
  app/src/main/java/com/sopt/aladinaos/presentation/MainActivity.kt
  app/src/main/java/com/sopt/aladinaos/util/binding/BindingActivity.kt
  app/src/main/java/com/sopt/aladinaos/util/binding/BindingFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: chore, pull request🔥, 영주🐼

#9 #7 [feat] 기초 네트워크 작업
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/aladinaos/data/di/LocalSourceModule.kt
  app/src/main/java/com/sopt/aladinaos/data/di/RemoteSourceModule.kt
  app/src/main/java/com/sopt/aladinaos/data/di/RetrofitModule.kt
  app/src/main/java/com/sopt/aladinaos/data/service/CartService.kt
  app/src/main/java/com/sopt/aladinaos/data/service/DetailService.kt
  app/src/main/java/com/sopt/aladinaos/data/service/HomeService.kt
  app/src/main/java/com/sopt/aladinaos/data/source/local/LocalDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/local/LocalDataSourceImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteCartDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteCartDataSourceImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteDetailDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteDetailDataSourceImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/sopt/aladinaos/presentation/AladinApplication.kt
Labels: feat, pull request🔥, 영주🐼

#6 #5 [ui] main / 바텀 내비게이션 구현
  .idea/workspace.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/aladinaos/presentation/cart/CartActivity.kt
  app/src/main/java/com/sopt/aladinaos/presentation/cart/CartFragment.kt
  app/src/main/java/com/sopt/aladinaos/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/aladinaos/presentation/main/MainActivity.kt
  app/src/main/java/com/sopt/aladinaos/presentation/profile/ProfileFragment.kt
  app/src/main/res/drawable/ic_bot_cart_unchecked.xml
  app/src/main/res/drawable/ic_bot_home_unchecked.xml
  app/src/main/res/drawable/ic_bot_profile_unchecked.xml
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/menu/menu_bot_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ui, pull request🔥, 영주🐼

#13 #12 [chore] Text Appearace, ci 추가
  app/build.gradle
  app/src/androidTest/java/com/sopt/aladinaos/ExampleInstrumentedTest.kt
  app/src/main/java/com/sopt/aladinaos/data/di/RetrofitModule.kt
  app/src/main/java/com/sopt/aladinaos/presentation/AladinApplication.kt
  app/src/main/java/com/sopt/aladinaos/presentation/main/MainActivity.kt
  app/src/main/res/font/pretendard.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.xml
  app/src/main/res/font/pretendard_mid.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semi_bold.otf
  app/src/main/res/font/pretendard_semibold.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/colors.xml
  app/src/test/java/com/sopt/aladinaos/ExampleUnitTest.kt
  build.gradle
Labels: chore, pull request🔥, 영주🐼

#18 #17 [fix] 서버 기초세팅 수정
  app/build.gradle
  app/src/main/java/com/sopt/aladinaos/di/LocalSourceModule.kt
  app/src/main/java/com/sopt/aladinaos/di/RemoteSourceModule.kt
  app/src/main/java/com/sopt/aladinaos/di/RetrofitModule.kt
Labels: fix, pull request🔥, 영주🐼

#16 #10 [ui] detail / 책 상세 뷰 구현
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/aladinaos/presentation/detail/DetailActivity.kt
  app/src/main/res/drawable/ic_detail_back.xml
  app/src/main/res/drawable/ic_detail_cart.xml
  app/src/main/res/drawable/ic_detail_gift.xml
  app/src/main/res/drawable/ic_detail_heartcircle_checked.xml
  app/src/main/res/drawable/ic_detail_heartcircle_unchecked.xml
  app/src/main/res/drawable/ic_detail_left.xml
  app/src/main/res/drawable/ic_detail_more.xml
  app/src/main/res/drawable/ic_detail_profile.xml
  app/src/main/res/drawable/ic_detail_right.xml
  app/src/main/res/drawable/ic_detail_search.xml
  app/src/main/res/drawable/ic_detail_write_review.xml
  app/src/main/res/drawable/img_detail_aladin.xml
  app/src/main/res/drawable/img_detail_badge.xml
  app/src/main/res/drawable/img_detail_carpet_delivery.xml
  app/src/main/res/drawable/img_detail_heart.xml
  app/src/main/res/drawable/img_detail_review_star.xml
  app/src/main/res/drawable/img_detail_star.xml
  app/src/main/res/drawable/sel_detail_heartcircle.xml
  app/src/main/res/drawable/shape_blue_fill_12_rect.xml
  app/src/main/res/drawable/shape_blue_line_12_rect.xml
  app/src/main/res/drawable/shape_g1_fill_12_rect.xml
  app/src/main/res/drawable/shape_gray_topline_rect.xml
  app/src/main/res/drawable/shape_white_fill_8_rect.xml
  app/src/main/res/drawable/shape_white_fill_g3_line_8_rect.xml
  app/src/main/res/drawable/shape_white_fill_shadow_rect.xml
  app/src/main/res/drawable/shape_yellow_fill_8_rect.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  gradlew
  gradlew.bat
Labels: ui, pull request🔥, 채연🐸

#21 #14 [ui] profile / 마이페이지 프래그먼트 구현
  app/src/main/res/drawable/ic_profile_more.xml
  app/src/main/res/drawable/img_profile_badge_silver.xml
  app/src/main/res/drawable/img_profile_profile.xml
  app/src/main/res/drawable/shape_bluegray_fill_g3_line_12_rect.xml
  app/src/main/res/drawable/shape_gl_topline_rect.xml
  app/src/main/res/drawable/shape_white_fill_12_rect_shadow.xml
  app/src/main/res/drawable/shape_white_fill_rect_shadow.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ui, pull request🔥, 채연🐸

#23 #15 [ui] cart / 장바구니 ui 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/aladinaos/AladinApplication.kt
  app/src/main/java/com/sopt/aladinaos/data/entity/response/BaseResponse.kt
  app/src/main/java/com/sopt/aladinaos/data/entity/response/Book.kt
  app/src/main/java/com/sopt/aladinaos/data/repository/CartRepository.kt
  app/src/main/java/com/sopt/aladinaos/data/repository/CartRepositoryImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/service/CartService.kt
  app/src/main/java/com/sopt/aladinaos/data/source/local/LocalDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/local/LocalDataSourceImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/source/local/LocalPrefDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteCartDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteCartDataSourceImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteDetailDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteDetailDataSourceImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/sopt/aladinaos/di/LocalSourceModule.kt
  app/src/main/java/com/sopt/aladinaos/di/RemoteSourceModule.kt
  app/src/main/java/com/sopt/aladinaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/aladinaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/aladinaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/aladinaos/di/SharedPrefModule.kt
  app/src/main/java/com/sopt/aladinaos/presentation/AladinApplication.kt
  app/src/main/java/com/sopt/aladinaos/presentation/cart/CartActivity.kt
  app/src/main/java/com/sopt/aladinaos/presentation/cart/CartAdapter.kt
  app/src/main/java/com/sopt/aladinaos/presentation/cart/CartFragment.kt
  app/src/main/java/com/sopt/aladinaos/presentation/cart/CartViewModel.kt
  app/src/main/java/com/sopt/aladinaos/util/ItemDiffCallback.kt
  app/src/main/java/com/sopt/aladinaos/util/binding/BindingAdapters.kt
  app/src/main/res/drawable/ic_cart_back.xml
  app/src/main/res/drawable/ic_cart_checked.xml
  app/src/main/res/drawable/ic_cart_unchecked.xml
  app/src/main/res/drawable/selector_cart_check.xml
  app/src/main/res/drawable/shape_grey4_fill_0_rect.xml
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/item_cart_body.xml
  app/src/main/res/values/strings.xml
Labels: ui, pull request🔥, 영주🐼

#25 #22 [ui/feat] detail / 책 상세 뷰 액티비티 구현
  app/build.gradle
  app/src/main/java/com/sopt/aladinaos/data/entity/response/Add.kt
  app/src/main/java/com/sopt/aladinaos/data/entity/response/Detail.kt
  app/src/main/java/com/sopt/aladinaos/data/entity/response/Like.kt
  app/src/main/java/com/sopt/aladinaos/data/entity/response/RequestAddToCartDto.kt
  app/src/main/java/com/sopt/aladinaos/data/repository/AddRepository.kt
  app/src/main/java/com/sopt/aladinaos/data/repository/AddRepositoryImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/repository/DetailRepository.kt
  app/src/main/java/com/sopt/aladinaos/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/repository/LikeRepository.kt
  app/src/main/java/com/sopt/aladinaos/data/repository/LikeRepositoryImpl.kt
  app/src/main/java/com/sopt/aladinaos/data/service/DetailService.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteAddDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteDetailDataSource.kt
  app/src/main/java/com/sopt/aladinaos/data/source/remote/RemoteLikeDataSource.kt
  app/src/main/java/com/sopt/aladinaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/aladinaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/aladinaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/aladinaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/aladinaos/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/aladinaos/util/ToastUtil.kt
  app/src/main/java/com/sopt/aladinaos/util/binding/BindingAdapters.kt
  app/src/main/res/drawable/shape_4_rect_shadow.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/values/strings.xml
Labels: feat, ui, 채연🐸

#26 #19 [feat] home / 서버 통신 구현
  .idea/.gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/aladinaos/data/HomeFactory.kt
  app/src/main/java/com/sopt/aladinaos/data/entity/response/HomeData.kt
  app/src/main/java/com/sopt/aladinaos/data/service/HomeService.kt
  app/src/main/java/com/sopt/aladinaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/aladinaos/presentation/home/HomeEditorChoiceAdapter.kt
  app/src/main/java/com/sopt/aladinaos/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/aladinaos/presentation/home/HomeTopsellerAdapter.kt
  app/src/main/java/com/sopt/aladinaos/presentation/home/HomeViewModel.kt
  app/src/main/res/drawable/ic_editor_selection.xml
  app/src/main/res/drawable/ic_home_back.xml
  app/src/main/res/drawable/ic_home_badge.xml
  app/src/main/res/drawable/ic_home_best.xml
  app/src/main/res/drawable/ic_home_book_background.xml
  app/src/main/res/drawable/ic_home_book_background_trans.xml
  app/src/main/res/drawable/ic_home_book_foreign.xml
  app/src/main/res/drawable/ic_home_book_kor.xml
  app/src/main/res/drawable/ic_home_category.xml
  app/src/main/res/drawable/ic_home_ebook.xml
  app/src/main/res/drawable/ic_home_event.xml
  app/src/main/res/drawable/ic_home_goods.xml
  app/src/main/res/drawable/ic_home_goods_banner.png
  app/src/main/res/drawable/ic_home_new.xml
  app/src/main/res/drawable/ic_home_toolb_barcode.xml
  app/src/main/res/drawable/ic_toolb_home_menu.xml
  app/src/main/res/drawable/ic_toolb_home_search.xml
  app/src/main/res/drawable/img_home_banner.png
  app/src/main/res/drawable/shape_home_g5_fill_12_rect.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_editor_choice.xml
  app/src/main/res/layout/item_home_topseller.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, ui, pull request🔥, 지영🐱

#29 #28 [fix] detail / Json Converter Factory 추가 및 할인율 구현
  app/build.gradle
  app/src/main/java/com/sopt/aladinaos/data/entity/response/Detail.kt
  app/src/main/java/com/sopt/aladinaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/aladinaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/aladinaos/presentation/detail/DetailViewModel.kt
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: fix, pull request🔥, 채연🐸

#31 #30 [fix] Gradle version 수정
  app/src/main/java/com/sopt/aladinaos/presentation/detail/DetailViewModel.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: fix, pull request🔥, 채연🐸
